version: '3.7'

services:
  super-bot-discord:
    image: gfaraj/super-bot-discord:latest
    build: .
    hostname: superbotdiscord
    env_file: 
      - .env
    environment:
      NODE_ENV: production
      SUPERBOT_URL: http://host.docker.internal:3000/message
      CALLBACK_HOST: localhost
    ports:
      - "3003:3003"