version: '3.7'

services:
  super-bot-discord:
    image: gfaraj/super-bot-discord:latest
    build: .
    env_file: 
      - .env
    environment:
      NODE_ENV: development
      SUPERBOT_URL: http://host.docker.internal:3000/message
    ports:
      - 3003:3003
      - 9229:9229
    command: node --inspect=0.0.0.0:9229 bot.js